# Generated by Django 2.1.3 on 2019-02-10 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DestOffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='DestRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='InOutbound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='MailDespatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op_bal', models.IntegerField()),
                ('item_category', models.CharField(choices=[('RLT', 'registered letter'), ('OLT', 'ordinary letter'), ('RIT', 'registered item'), ('PAR', 'parcel'), ('EMS', 'EMS')], max_length=3)),
                ('date_sent', models.DateField(auto_now_add=True)),
                ('qty_sent', models.IntegerField()),
                ('date_received', models.DateField(auto_now_add=True)),
                ('qty_received', models.IntegerField()),
                ('qty_delivered', models.IntegerField()),
                ('cls_bal', models.IntegerField()),
                ('comment', models.TextField(max_length=100)),
                ('received_by', models.CharField(max_length=30)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('dest_office', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maildestinations', to='web.DestOffice')),
                ('dest_region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destinations', to='web.DestRegion')),
            ],
            options={
                'ordering': ('-created_on',),
            },
        ),
        migrations.CreateModel(
            name='PostOffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Transmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=15)),
                ('item_category', models.CharField(choices=[('RLT', 'registered letter'), ('OLT', 'ordinary letter'), ('RIT', 'registered item'), ('PAR', 'parcel'), ('EMS', 'EMS')], max_length=3)),
                ('sent_date', models.DateField(auto_now_add=True)),
                ('standard_days', models.IntegerField()),
                ('received_date', models.DateField()),
                ('days', models.PositiveIntegerField()),
                ('day_difference', models.IntegerField()),
                ('comment', models.TextField(max_length=100)),
                ('received_by', models.CharField(max_length=30)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('dest_postoffice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dest_office', to='web.PostOffice')),
                ('dest_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dest_region', to='web.Region')),
                ('postoffice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_office', to='web.PostOffice')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_region', to='web.Region')),
            ],
            options={
                'ordering': ('-created_on',),
            },
        ),
        migrations.AddField(
            model_name='postoffice',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postoffices', to='web.Region'),
        ),
        migrations.AddField(
            model_name='maildespatch',
            name='postoffice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='officedespatches', to='web.PostOffice'),
        ),
        migrations.AddField(
            model_name='maildespatch',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despatches', to='web.Region'),
        ),
    ]
