# Generated by Django 2.1.3 on 2019-02-11 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transmission',
            name='day_difference',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transmission',
            name='days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transmission',
            name='received_date',
            field=models.DateField(blank=True),
        ),
    ]
