# Generated by Django 2.1.3 on 2018-12-20 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=100)),
                ('received_date', models.DateTimeField()),
                ('sent_date', models.DateTimeField()),
                ('days', models.PositiveIntegerField()),
                ('source', models.CharField(max_length=100)),
                ('item_category', models.CharField(max_length=100)),
                ('item_id', models.IntegerField(null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_on',),
            },
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='city',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='client',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='zone',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
