# Generated by Django 2.1.3 on 2019-02-11 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20190211_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transmission',
            name='received_date',
            field=models.DateField(null=True),
        ),
    ]
