# Generated by Django 2.1.3 on 2019-02-20 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20190211_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maildespatch',
            name='received_by',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='transmission',
            name='day_difference',
            field=models.IntegerField(default=0, help_text='This is automatically calculated when the             received date is set'),
        ),
        migrations.AlterField(
            model_name='transmission',
            name='received_by',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='transmission',
            name='received_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
